괄호 먼저 계산하는 기능 구현 완료
th-kwon/Calculator pull request #4
Opened 2020-02-18 08:31 UTC by LeeJungGeun

클래스를 새로 추가하여 괄호의 내용은 따로 분리시켜 먼저 계산하도록함
그리고  그 결과값을 숫자 배열에 넣도록 변경

2020-02-18 08:41 UTC, LeeJungGeun commented
연산해야하는 숫자가 4개 이상이되면 에러발생하며 강제종료됨

Expression : string iterator not incrementable

2020-02-19 02:04 UTC, th-kwon requested changes
* 현재 코드상으로는 2중 괄호 연산이 되지 않을 것으로 예상됩니다. `ex) 4 + ( (2 + 3) * 2)`
  * 버그 수정 후 테스트까지 마치고 나서 Pull request해 주세요.
* 새로 변수/함수 작성시에는 적절한 이름을 사용해 주시고, 설명에 대해 주석을 달아 주도록 합시다. 
* 들여쓰기를 잘 해야 다른 사람이 보기 편하니 깔끔하게 만들어 줍시다.
  * 자동 들여쓰기 단축키 : `Ctrl+K, D` 입니다.(K->D)

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.cpp
> +int Gl2;
변수는 클래스 내에서 선언해 전역변수로 사용할 수 있도록 합시다.

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.h
> +	int calculate2();
함수 설명 코멘트로 간략하게 적어 주세요.

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.cpp
> +		while (itNumber != _vecNumbers2.end())
들여쓰기 깔끔하게 넣어 주세요.
```suggestion
	while (itNumber != _vecNumbers2.end())
```

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.cpp
> +				if (itOperator == _vecOperators2.end())
들여쓰기 깔끔하게 넣어 주세요.
```suggestion
			if (itOperator == _vecOperators2.end())
```

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.cpp
> +			}
들여쓰기 깔끔하게 넣어 주세요.
```suggestion
		}
```

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.cpp
> +		return _answer;
들여쓰기 깔끔하게 넣어 주세요.

2020-02-19 02:04 UTC, th-kwon commented on Calculator/Calculator_base.cpp
> +			calcute2();
지금 호출한 건 `함수`지, `클래스`가 아닙니다.
그리고 유사한 코드로 함수를 새로 만들어 호출하는 건 재귀호출이라고 보기 어렵습니다.
아래와 같은 형태로 만들어 보도록 합시다.
```suggestion
		Calculator subCalculator; // 클래스를 재귀호출
		subCalculator.SetQuestion(/*괄호 안쪽의 내용*/);
		subCalculator.Calculate(); // 재귀호출한 클래스에게 괄호 안쪽의 내용을 연산시킴
		numberInput = std::to_string(subCalculator.GetAnswer()); // 결과를 받아와 numberInput에 저장
```

2020-02-19 08:08 UTC, closed without merging